batch_size: 128
classifier: resnet18
data_dir: data
dev: 0
download_weights: 0
filepath: /home/yifan/0ExpMinist/Noise_pairflip
gpu_id: '0'
learning_rate: 0.005
logger: tensorboard
max_epochs: 20
noise_rate: 0.2
noise_type: symmetric
num_workers: 2
period: 1
precision: 32
pretrained: 0
save_top_k: -1
test_phase: 0
weight_decay: 0.01
